config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/pets', to: 'pets#index'
  # http verb path, to: controllername#action_name


  get '/pets/new', to: 'pets#new'
  post '/pets', to: 'pets#create'

  get 'pets/:id', to: 'pets#show', as: :pet

  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'

  delete '/pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat snake turtle unicorns)
  validates :name, presence: true
  validates :specie, inclusion: {in: SPECIES}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
    # raise
    # @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    # raise
    @pet = Pet.create(strong_params_pet)
    redirect_to pet_path(@pet)
  end

  def edit
    # @pet = Pet.find(params[:id])
  end

  def update
    # @pet = Pet.find(params[:id])
    @pet.update(strong_params_pet)
    redirect_to pets_path
  end

  def destroy
    # @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end


  private

  def strong_params_pet
    params.require(:pet).permit(:name, :address, :found_on, :specie)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<!-- WITH FORM FOR -->
<%#= form_for mango do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name%>

  <%#= f.label :address%>
  <%#= f.text_field :address%>

  <%#= f.label :found_on%>
  <%#= f.date_field :found_on%>

  <%#= f.label :specie%>
  <%#= f.text_field :specie %>

<%#= f.submit %>
<%# end %>


<!-- WITH SIMPLE FORM FOR-->

<div class="container">
  <div class="row">
  <%= simple_form_for mango do|f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :found_on %>
  <%= f.input :specie , collection: Pet::SPECIES %>
  <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<!-- <form action="/pets/<%= @pet.id %>" method="post">
  <%#= hidden_field_tag :authenticity_token, :form_authenticity_token %>
  <input type="hidden" name="_method" value="patch">
  <label for="">name</label>
  <input type="text" name="pet[name]" value="<%#= @pet.name %>">
  <label for="">address</label>

  <input type="text" name="pet[address]" value="<%#= @pet.address %>">
  <label for="">found_on</label>

  <input type="text" name="pet[found_on]" value="<%#= @pet.found_on %>">
  <label for="">specie</label>

  <input type="text" name="pet[specie]" value="<%#= @pet.specie %>">
  <input type="submit">
</form>


 -->

<!-- form for -->

<%#= form_for @pet do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name%>

  <%#= f.label :address%>
  <%#= f.text_field :address%>

  <%#= f.label :found_on%>
  <%#= f.date_field :found_on%>

  <%#= f.label :specie%>
  <%#= f.text_field :specie %>

<%#= f.submit %>
<%# end %>

<%= render 'form', mango: @pet %>

app/views/pets/index.html.erb
<div class="container">
<h1>Pets</h1>
<% @pets.each do |pet|%>
<h1> <%= link_to pet.name, pet_path(pet) %></h1>
  <p><%= pet.address %></p>
 <p> <%= pet.specie %></p>
  <%= pet.found_on %>
  <%= link_to 'destroy', pet_path(pet), method: :delete, data: { confirm: 'Are you sure ?'} %>
<% end %>
</div>

app/views/pets/new.html.erb
<!-- WITH HTML -->
<!-- <form action="/pets" method="post">
  <%#= hidden_field_tag :authenticity_token, :form_authenticity_token %>
  <label for="">name</label>
  <input type="text" name="pet[name]">
  <label for="">address</label>

  <input type="text" name="pet[address]">
  <label for="">found_on</label>

  <input type="text" name="pet[found_on]">
  <label for="">specie</label>

  <input type="text" name="pet[specie]">
  <input type="submit">
</form>
 -->


<!-- WITH FORM FOR -->
 <%#= form_for @pet do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name%>

  <%#= f.label :address%>
  <%#= f.text_field :address%>

  <%#= f.label :found_on%>
  <%#= f.date_field :found_on%>

  <%#= f.label :specie%>
  <%#= f.text_field :specie %>

<%#= f.submit %>
<%# end %>

<%= render 'form', mango: @pet %>

app/views/pets/show.html.erb
<div class="container">

<h1> <%= @pet.name %></h1>
<p> <%= @pet.address %></p>
 <p>  <%= @pet.specie %></p>

  <%= @pet.found_on %>
  <p><%= link_to 'edit', edit_pet_path(@pet)  %></p>
  <p><%= link_to 'Back home', pets_path  %></p>

</div>